import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Revista EDUCARTE I.S.C</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap" rel="stylesheet" />
      </Head>

      <main className="w-screen h-screen bg-gray-900 font-sans text-white">
        <nav className="w-screen bg-gray-800">
          <ul className="flex justify-evenly p-3">
            <li className="">Inicio</li>
            <li className="">Inicio</li>
            <li className="">Inicio</li>
            <li className="">Inicio</li>
          </ul>
        </nav>
        <section id="content" className="grid grid-cols-1 gap-32 grid-row text-center p-5">
          <article id="magazine">
            <h1 className="text-7xl p-3">EDUCARTE</h1>
            <h2 className="w-max sm:w-80 md:w-96 m-auto">Revista digital realizada por alumnos de quinto año del Instituto San Carlos de Malagueño, Córdoba, Argentina.</h2>
          </article>
          <article id="about">
            <h3 className="text-3xl p-2">Acerca de EDUCARTE</h3>
            <div className="bg-gray-100 text-black rounded-md">
              <p className="p-3"><strong>EDUCARTE</strong> es una revista digital lanzada mensualmente por los estudiantes de quinto año del Instituto San Carlos de Malagueño. Incluye temas de interés y cultura general, como literatura, arte, música, tradiciones y muchas cosas más que no se limitan solo a nuestro país.</p>
            </div>
          </article>
          <article id="editions">
            <h3 className="text-3xl p-2">Ediciones</h3>
          </article>
        </section>
      </main>
    </div>
  )
}
